### PR TITLE
Created userscript version

### PR DESCRIPTION
**Pull request by HelloWorld017**

### CODE REVIEW

**Comment by jasonlong** [comment]
Wow very cool, thanks @HelloWorld017! I will give this a try soon and I'll be happy to merge it if it works ok.

**Comment by HelloWorld017** [comment]
Thanks!
Also, before merge, adding update link to the userscript would be good!

**Comment by jasonlong** [comment]
@HelloWorld017 I verified that the userscript works great on Chrome w/ Tampermonkey, but I'm having trouble with Safari and Firefox.

I'm using Safari w/ Tampermonkey and it shows as enabled, but the chart doesn't render.

image

In Firefox, I tried Greasemonkey and it's not working either. (Ignore the "Unnamed Script" naming).

image

I haven't used userscripts very much in the past, so these problems could definitely be user error. 😜

**Comment by HelloWorld017** [comment]
I've installed firefox and just removed run-at document-body statement, which is only available in Tampermonkey and not available in Greasemonkey. :D

**Comment by jasonlong** [comment]
Sorry for the delay @HelloWorld017. I confirmed that Firefox/Greasemonkey now works great.

I still don't see it working in Safari/Tampermonkey for some reason. Any ideas?

screen shot 2018-03-14 at 8 54 54 pm

**Comment by HelloWorld017** [comment]
Sorry for late answer T_T

I really want to check that issue, but I have no mac to test on Safari.
Would you check if there are errors on browser console?

**Comment by jasonlong** [comment]
I attempted some more debugging today and ended up more confused. 

There are no console errors, but digging further, I realized that the script isn't even running in Safari. I started a brand new minimal script that targets github.com and it doesn't run. I changed the same script to target cnn.com and it does run.

So something seems to be unique to github.com, but that doesn't make much sense either because I'm using Tampermonkey in Chrome as well and it works fine there.

I'm going to be out of town this week, so I won't have any more time to look into this, but will take a look when I get back. Unless someone else beats me to it! 😄

**Comment by jasonlong** [comment]
Closing this for now, but feel free to reopen.

**Pull request closed without merging**
