### PR TITLE
Update for new GitHub colors

### PR DESCRIPTION
**Pull request by Matt-Gleich**
I could only change the chrome and firefox extensions as I don't know how to change it for safari.

### CODE REVIEW

**Comment by Matt-Gleich** [comment]
This PR resolves #110

**Comment by Fasani** [comment]
Hi Matt, I wonder if you missed the color of the text counts in the view. 

‘’’css
.ic-stats-count {
  ...
  color: #1e6823;
}
‘’’

**Comment by Fasani** [comment]
Sorry reviewing via my mobile.

**Comment by Matt-Gleich** [comment]
No worries didn't know if you wanted that changed. Committing now.

**Comment by jasonlong** [comment]
Thanks for working on this @Matt-Gleich! I'm noticing some other things that need to change as part of this, so I can just add some commits to your branch if you don't mind?

**Comment by Matt-Gleich** [comment]
Yep sounds good!

**Comment by Matt-Gleich** [comment]
Looks like I put two of the colors wrong last night. Fixed now!

**Comment by Fasani** [comment]
I am getting excited about the outcome!

**Comment by waldyrious** [comment]
Just a heads-up that the [preview image](http://cl.ly/image/1j0j3l1R1d2Z/content) in the README should also be updated. If I may add, IMO it should be tracked in the repo, rather than hosted externally, so that design changes like this will be visually documented.

@jasonlong I can submit a separate PR adding the image as a file in the repo, so that this PR can change it to the new preview image and provide the first such visual diff — WDYT?

**Comment by jasonlong** [comment]
@waldyrious I didn't remember that the image was hosted elsewhere, but yes I agree it should be here. Feel free to submit that PR with the current image. I have some other visual tweaks in mind and, along with these color updates, I'll update that new image at that time.

**Comment by jasonlong** [comment]
Ok, I got myself into a merge conflict, but I think I have all the new colors accounted for – including our newer text colors from Primer.

Here's how things look now:

image

**Comment by jasonlong** [comment]
Thanks again @Matt-Gleich

**Comment by jasonlong** [comment]
Well this is annoying – Chrome now has a review system for extensions so who knows how long this will take `1.0.30` to make it out to everyone.

If anyone wants to install the dev version yourselves, you can follow the instructions in the [README](https://github.com/jasonlong/isometric-contributions#developer-mode).

**Comment by Fasani** [comment]
Just an FYI, it's already on the store so no need to instal dev version.

Also, the graphics on the chrome store are now out of date and could be updated also.

Screenshot 2020-06-25 at 12 54 17

**Comment by jasonlong** [comment]
Yes, the 1.0.30 release was approved surprisingly fast. 

I'm going to update the screenshots here and on the Chrome store once I made a few more design tweaks.

**Pull request merged**
