### PR TITLE
Long numbers

### PR DESCRIPTION
**Pull request by KimDarren**
* The numbers, bigger than a thousand, in the `Longest streak` and Current streak` was not shown. So I fix some regex.

## Before

bef

## After

af

### CODE REVIEW

**Comment by jasonlong** [comment]
Wow, that's a heck of a streak! Thanks for the update. :sparkles:

**Comment by jasonlong** [comment]
Version 1.0.7 is now in the Chrome web store with this fix.

**Comment by KimDarren** [comment]
Thx to merge my request :+1:

**Comment by KimDarren** [comment]
My commits are generated by [git-faker](https://github.com/KimDarren/git-faker) :smile:

**Pull request merged**
