### PR TITLE
Check for Hex colors not yet defined to display.

### PR DESCRIPTION
**Pull request by shadoath**
Halloween colors must show!

### CODE REVIEW

**Comment by jasonlong** [comment]
:ghost: Gah, I dropped the ball on this again this year.

@shadoath Could you make this change to `src/iso.coffee`? The file you changed is one of the generated files from that source file.

This reminds me, I need to port that file from coffeescript one of these days.

**Comment by shadoath** [comment]
@jasonlong the `src/iso.coffee` is now updated. 
Do you want a compiled updates to be added as well? I have coffee 2.0.2 installed but I see you have coffee 1.10.0 used for the last build.

**Comment by strikemike2k** [comment]
Yes! I woke up this morning and was disappointed to see a non-colored isometric contributions display. I'm glad to see this being updated to support the awesome Halloween colors!

**Comment by shadoath** [comment]
screen shot 2017-10-31 at 12 37 00 pm
Halloween Magic!

**Comment by jasonlong** [comment]
@shadoath Yeah, go ahead and commit those generated files too. I built them locally and it looks good! Thanks for the update!

**Comment by jasonlong** [comment]
The new version has been uploaded to the Chrome Web Store and should be available shortly.

**Pull request merged**
