### PR TITLE
Fix #108

### LINKED ISSUE #108: Switching between views causes year list to move out of view
When you switch between views (isometric and normal) the year list below it moves out of view. See the image below 
Screenshot 2020-03-05 at 5 00 57 PM

### PR DESCRIPTION
**Pull request by zhmushan**
I don't know why, but it does work.

### CODE REVIEW

**Comment by zhmushan** [comment]
@jasonlong anyone there?

**Comment by jasonlong** [comment]
Hi @zhmushan, sorry for the delay. Thank you very much for your fix here. I haven't merged this yet because the fact that we need this sort of hack tells me maybe I'm using the wrong element here. I've been meaning to see if a `<button>` would work instead (removing the standard styling). 

I'm planning on trying that out, but you're welcome to as well if you like.

**Comment by zhmushan** [comment]
@jasonlong sorry, my CSS skill is poor, close this pr.

**Comment by jasonlong** [comment]
@zhmushan Oh no, this bug is my fault not yours! I will try to get this fixed up with the `<button>` element soon. Thanks again for bringing this to my attention. :)

**Pull request closed without merging**
