### PR TITLE
[WIP] Common code base for all extensions

### PR DESCRIPTION
**Pull request by deltaidea**
- Some users prefer the chart to be smaller but to fit into the contributions element. This PR makes this an option rather than forcing one way or another on all users.
- To consolidate codebase, `iso.coffee` is moved to `src/` and then compiled to extensions from there.
- This PR also fixes for chart flickering on page load.

Please review individual commits for more information.

Thank you for this awesome extension!

### CODE REVIEW

**Comment by jasonlong** [comment]
I'd rather not add the extra option and complexity of rendering different size blocks. I haven't heard of anyone wanting them to be smaller.

The other changes seem solid though. 👍

**Comment by deltaidea** [comment]
Agreed, no problem, I'll tidy up this PR and leave the block size setting in my fork. :+1:

**Comment by jasonlong** [comment]
I just noticed that this uses the same `iso.coffee` for all three browsers, but IIRC each has some different code in place for local storage. Were you able to coming up with something that works across the board?

**Comment by deltaidea** [comment]
I used a modified version of what Firefox has now. It uses `chrome.storage` when available with a fallback to `localStorage`.

**Pull request closed without merging**
