### PR TITLE
Improvements to README.md

### PR DESCRIPTION
**Pull request by IgorAntun**
Because why not? ;)

### CODE REVIEW

**Comment by jasonlong** [comment]
Thanks @IgorAntun. I'm pretty happy with the existing README (especially the blank lines under the headings), but I think removing the `$` from the command and adding the alt text to the image are good ideas. If you want to update this PR w/ just those things, that would be cool. Otherwise I can tackle those separately.

**Comment by rileyjshaw** [comment]
It looks to me like a `$` was _added_ here. This seems like an antipattern; lots of people accidentally copy the  `$` along with the rest of the command. I've always found that a clearer pattern is just to say:

> In your terminal, type:
```
coffee -cb iso.coffee
```

**Comment by jasonlong** [comment]
Derp, you're right @rileyjshaw – I scanned the diff incorrectly. I definitely think the `$` should be omitted.

**Comment by jasonlong** [comment]
Since the alt text is the only thing ending up being changed here, I went ahead and made that update separately. I'm going to go ahead and close this, but thanks for the :eyes: @IgorAntun.

**Comment by IgorAntun** [comment]
No problem :)

**Pull request closed without merging**
